### ISSUE TITLE
TypeError su authn_request.py:test_Conditions

### ISSUE THREAD

**Issue by AndreaPetrelli** [italia/spid-sp-test#102]
Sto usando il tool spid-saml-check con docker (OSX) che installa questa libreria tramite pip3 (0.9.16.post1)

La chiamata della funzione test_Conditions dentro il file authn_request.py fallisce alle chiamate _assertTrue con questo errore:

**TypeError: _assertTrue() got multiple values for keyword argument 'description'**

infatti variabile "description" è contenuta anche nel dizionario "_data".

Provando a correggere rimuovendo il parametro description dalle chiamate _assertTrue dentro la funzione test_Conditions ottengo un altro errore alla riga 930:

**AttributeError: module 'spid_sp_test.constants' has no attribute 'regex'**

**Comment by peppelinux** [comment]
Grazie, corretto qui
https://github.com/italia/spid-sp-test/commit/436363af9eaf916213ff895fbc9bbcee91b14d19

Adesso puoi aggiornare spid-sp-test alla versione 0.9.17
