### ISSUE TITLE
TypeError su authn_request.py:test_Conditions

### ISSUE THREAD

**Issue by AndreaPetrelli** [italia/spid-sp-test#104]
C'è ancora un errore nella funzione test_Conditions del file authn_request.py

**TypeError: _assertTrue() got multiple values for keyword argument 'description'**

ed il motivo è lo stesso del fix #102 (variabile "description" è contenuta anche nel dizionario "_data".) ma alla riga 931

**Comment by peppelinux** [comment]
Grazie @AndreaPetrelli 
eccoci
https://pypi.org/project/spid-sp-test/0.9.19/
