### ISSUE TITLE
ACR reponse check should consider "Comparison" attribute

### ISSUE THREAD

**Issue by ewedlund** [italia/spid-sp-test#111]
According to the documentation, the accepted AuthnContextClassRef depends on the attribute "Comparison". Currently, the method 
https://github.com/italia/spid-sp-test/blob/6a9302a210c6f6b80a172ad876716433787857f3/src/spid_sp_test/responses/response_mods.py#L5
takes for granted that Comparison=="minimum", which makes e.g. test n. 96 fail for the case when Comparison="exact".

Valid Comparison values are 

exact
minimum
better
maximum

Not sure how "better" and "maximum" should be handled. I propose to at least add handling "exact".

**Comment by peppelinux** [comment]
closed by https://github.com/italia/spid-sp-test/pull/112
