### ISSUE TITLE
Malfunzionamento alcuni IDP

### ISSUE THREAD

**Issue by comunedimisanoadriatico** [italia/spid-sp-test#116]
Buongiorno, sul sito https://misanoadriatico.comune.plugandpay.it/ vi è la problematica di alcuni IDP che riscontrano un "errore inatteso". In particolare si tratta di Lepida, Spiditalia Register.it, Aruba, mentre altri IDP (es. Poste, Infocert) consentono l'accesso.
A seguito di numerose segnalazioni abbiamo richiesto la disabilitazione del pulsante di accesso all'area riservata, ma si voleva comprendere quale può essere la problematica.

**Comment by peppelinux** [comment]
buondì,

questa problematica non può essere gestita all'interno del progetto spid-sp-test ma usando i canali di assistenza ufficiali di AgID. Si consiglia di scrivere a spid-tech@agid.gov.it e di contattare gli IDP come di seguito indicato:

https://www.spid.gov.it/ottieni-assistenza-dagli-identity-provider/
