### ISSUE TITLE
Private Spid SP Aggregatore Full/Light check missing

### ISSUE THREAD

**Issue by ExperianDev** [italia/spid-sp-test#126]
I'm trying to validate medatata for private service full aggregator, but it seems that relevant profile is not still implemented in both spid-saml-check and spid-sp-test

I've opened this issue as suggested by @peppelinux

**Comment by peppelinux** [comment]
ciao @ExperianDev 

abbiamo iniziato qui ad implementare i profili per SA privati insieme @nunzionapoli 
https://github.com/italia/spid-sp-test/commit/ed32a48b8b2a8c3036c61cfe5ec127b6181a7e84

testiamo e revisioniamo, se hai voglia unisciti pure, rilasceremo v1.2.0 con questo appena possibile

**Comment by ExperianDev** [comment]
Grazie mille ragazzi

**Comment by peppelinux** [comment]
la release è in via di collaudo lato AgID su branch dev

**Comment by peppelinux** [comment]
done here

https://github.com/italia/spid-sp-test/pull/132
