### ISSUE TITLE
Missing support for "companyFiscalNumber" attribute

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid-sp-test#13]
Missing support for "companyFiscalNumber" attribute, as defined in[ Avviso SPID n°15](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n15-_rilascio_identita_uso_professionale.pdf)

**Comment by peppelinux** [comment]
Ok, we can add It in src/spid_sp_test/responses/settings.py

Or you can even define It in a customized attributes JSON file, passed with -aj option.

Please, give a chance to -aj and tell me what do you think about It

A commit to add that attributes in the standard settings would be trivial, sure I Will, thank you

**Comment by peppelinux** [comment]
here
https://github.com/italia/spid-sp-test/releases/tag/0.5.1

**Comment by peppelinux** [comment]
thanks to your contribute, updated here:
https://github.com/italia/spid-sp-test/releases/tag/0.5.2
