### ISSUE TITLE
Validazione ambiente aggregato fittizio

### ISSUE THREAD

**Issue by SimoneAcca** [italia/spid-sp-test#134]
Salve,

Vorrei eseguire una validazione per un ambiente aggregato privato fittizio (usato poi per il collaudo) però continuo ad ottenere il seguente errore sul vat Number:

`ERROR:spid_sp_test.metadata:The VATNumber element MUST start with a valid ISO3166 Code`

Sulla documentazione però viene riportato che per l'ambiente fittizio il vat Number debba essere specificato nel seguente modo.

`<spid:VATNumber>__aggrsint</spid:VATNumber>`

**Comment by peppelinux** [comment]
Risolto qui
https://github.com/italia/spid-sp-test/pull/139/files
