### ISSUE TITLE
Errore di validazione con profilo cie-sp-public

### ISSUE THREAD

**Issue by fmartelli** [italia/spid-sp-test#141]
Validando con il profilo cie-sp-public vengono rilevati erroneamente i seguenti errori

```
ERROR:spid_sp_test:Test [70] Attributo Format di Issuer dell'Assertion non specificato. Risultato atteso: KO
ERROR:spid_sp_test:Test [71] Attributo Format di Issuer dell'Assertion mancante. Risultato atteso: KO
```
Stando alle specifiche CIE (https://docs.italia.it/italia/cie/cie-manuale-tecnico-docs/it/master/protocolli.html#risposta-di-autenticazione-saml) ed in particolare alla nota circa la compatibilità con SPID riguardo la validazione della risposta inviata dall'IdP, risulta evidente il baco. Si legge infatti

```
Con riferimento alla compatibilità con SPID si riporta quanto segue:

    L’attributo Format dell’elemento <samlp:Issuer> non è presente;
```

**Comment by peppelinux** [comment]
contributo unito, non l'abbiamo ancora in relase ma lo sarà alla prima possibile

**Comment by peppelinux** [comment]
Done here
https://github.com/italia/spid-sp-test/releases/tag/v1.2.3

Grazie @fmartelli
