### ISSUE TITLE
Critical error on metadata check

### ISSUE THREAD

**Issue by nunzionapoli** [italia/spid-sp-test#143]
Provando ad eseguire il seguente check :
spid_sp_test  --extra  --production --debug WARNING  -pr spid-sp-public --metadata-url 'https://registry.spid.gov.it/metadata/sp/fedna_rm.xml'
Si ottiene il seguent errore 
CRITICAL:__main__:Errors occourred during Check, <class 'spid_sp_test.metadata_extra.SpidSpMetadataCheckExtra'>: [Errno Expecting value] com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 14, column: 20] (through reference chain: it.ipa.portale.dto.RicercaAooRequest[&quot;codEnte&quot;]): 0

**Comment by peppelinux** [comment]
in get_indicepa_by_ipacode otteniamo

`om.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value\n at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 14, column: 20] (through reference chain: it.ipa.portale.dto.RicercaAooRequest[&quot;codEnte&quot;])`

e il problema è che il valore non è pulito

````
(Pdb++) print(qs_final)

    {"paginazione":
        {"campoOrdinamento":"codAoo",
         "tipoOrdinamento":"asc",
         "paginaRichiesta":1,
         "numTotalePagine":null,
         "numeroRigheTotali":null,
         "paginaCorrente":null,
         "righePerPagina":null},
         "codiceFiscale":null,
         "codUniAoo":null,
         "desAoo":null,
         "denominazioneEnte":null,
         "codEnte":"
                fedna_rm
            ",
         "codiceCategoria":null,
         "area":null
    }
````

questo errore è stato qui risolto
https://github.com/italia/spid-sp-test/commit/cceb61d01f4793cfeda89f93787cf5867134bca4
