### ISSUE TITLE
Errore validazione email dominio .digital (Test 66) 

### ISSUE THREAD

**Issue by claudiominucci** [italia/spid-sp-test#150]
Buongiorno,
ho un errore sul test 66 utilizzando una mail con dominio ".digital". 
Sembra che attualmente l'espressione regolare utilizzata per la verifica permetta domini con al massimo 6 caratteri.

**Comment by peppelinux** [comment]
Ciao, grazie per l'hint, correggo subito

**Comment by peppelinux** [comment]
Risolto qui
https://github.com/italia/spid-sp-test/releases/tag/v1.2.9
