### ISSUE TITLE
Errore nella verifica della Authreq con il metodo HTTP-GET, se il parametro RelayState non è presente 

### ISSUE THREAD

**Issue by nunzionapoli** [italia/spid-sp-test#154]
Se il parametro RelayState non è presente nella URL della request,
la seguente assegnazione (riga 352 del file authn_reqest.py):
                authn_req = (
                    f"SAMLRequest={quoted_req}&"
                    f"RelayState={quoted_rs}&"
                    f"SigAlg={quoted_sigalg}"
                )
Inserisce  la stirnga "RelayState="  nel parametro verificato con openssl

**Comment by peppelinux** [comment]
Se il parametro relay state non fosse presente, dovremmo forse tornare direttamente con un errore?

Credo di sì, confermi?
