### ISSUE TITLE
Errore codice IPA non valido

### ISSUE THREAD

**Issue by trinko** [italia/spid-sp-test#163]
Segnalo che effettuando la validazione ottengo il seguente errore sul codice IPA:
"SPID Compliant Certificates Value for name attribute [Unknown OID, 2.5.4.97] must match ^PA:IT-\S{1,11}$"

Ma il codice IPA della mia scuola è più lungo di 11 caratteri (credo sia così per tutte le scuole): **istsc_catf04000p**

Il codice IPA è ovviamente corretto: [pagina consultazione IPA](https://indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente/scheda-ente/14402)

**Comment by peppelinux** [comment]
Ciao, lasciamo qui la issue ma ti chiedo di aprirla anche su SPID Compliant Certificates python perché il validatore è lì ed è una dipendenza in spid-sp-test

**Comment by trinko** [comment]
Grazie, ho aperto la issue su SPID Compliant Certificates python.

**Comment by peppelinux** [comment]
Risolto con la release 0.5.5 di spid-compliant-certificates-python
https://github.com/italia/spid-compliant-certificates-python/releases/tag/v0.5.5

@damikael ^
