### ISSUE TITLE
Compliant Certificates Value for name attribute 

### ISSUE THREAD

**Issue by nesar77** [italia/spid-sp-test#171]
Come soggetto aggregatore, in particolare  spid-sp-ag-public-full, la validazione del metadata, dopo la pubblicazione della versione 1.10.2, viene scartata a seguito del seguente errore: SPID Compliant Certificates Value for name attribute [Unknown OID, 2.5.4.97] must match ^PA:IT-\S{1,11}$ . 

La ca usata per generare il certificato di federazione riporta il valore VATIT-02762210041, così come richiesto nell'allegato [29 rev. 3](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n29v3-specifiche_sp_pubblici_e_privati.pdf) .

Un esempio di metadata è consultabile [qui](https://auth.portalecomuni.net/authsrv/metadata/c_i963__02762210041)

**Comment by peppelinux** [comment]
Ciao @nesar77 

aiutami a capire. Potrei sbagliarmi, mi pare che VATIT sia per soggetti privati, mentre il tuo SA risulta soggetto pubblico.

![immagine](https://github.com/italia/spid-sp-test/assets/1297620/2e9aa41b-bf32-40f3-93d0-b6564faf925c)

**Comment by nesar77** [comment]
Ciao @peppelinux ,

siamo privati che aggregano per soggetti pubblici e la nostra partita iva inizia per IT.

**Comment by peppelinux** [comment]
contatta spid tech informandola di qeusto e condividi qui ogni riferimento tecnico relativo al tuo profilo

**Comment by nesar77** [comment]
Grazie @peppelinux ,
su slack mi hanno consigliato di aprire una issue..
