### ISSUE TITLE
ForceAuthn should allow for '1' and '0' values

### ISSUE THREAD

**Issue by damikael** [italia/spid-sp-test#23]
SAML Core 2.0 defines value for ForceAuthn as a boolean. 
The primitive type xs:boolean as per W3C XML Schema can be true, false, 0, 1

https://github.com/italia/spid-saml-check/issues/93
https://github.com/italia/spid-saml-check/issues/36

Fix here:
https://github.com/italia/spid-saml-check/commit/f5b7159d5e464a345e7018d3df8c752cc57f6a7c

**Comment by peppelinux** [comment]
already here
https://github.com/italia/spid-sp-test/blob/2f5b84dad0c885d2c793e2b7c38b12dd69cc22f5/src/spid_sp_test/authn_request.py#L355
