### ISSUE TITLE
Check EntityID

### ISSUE THREAD

**Issue by damikael** [italia/spid-sp-test#25]
L'EntityID dichiarato nel metadata deve essere una URL, preferibilmente https, e deve corrispondere al dominio indicato nel parametro --metadata-url, quando questo è specificato come http o https.

Nel caso in cui non sia https o non corrisponda al dominio sul quale è pubblicato il metadata, il test deve fornire un warning (non errore)

Rif. https://github.com/italia/spid-saml-check/issues/114

**Comment by peppelinux** [comment]
features added

````
{
  "test": {
    "sp": {
      "metadata_strict": {
        "SpidSpMetadataCheck": [
          {
            "result": "success",
            "test": "SpidSpMetadataCheck.xsd_check"
          },
          {
            "result": "warning",
            "test": "The EntityID must be equal to http://localhost:8000/spid/metadata",
            "value": "http://localhost:8000/spid/metadata/"
          },

...

````
