### ISSUE TITLE
Profiles management

### ISSUE THREAD

**Issue by damikael** [italia/spid-sp-test#26]
spid-sp-test should handle different profiles where every profile contains some tests.
Same unique test can be used into more different profiles.
Profiles could be defined into configuration files as for Response Test Suite.
A single profile can be executed as follow, for example:

`spid_sp_test --metadata-url http://localhost:8000/spid/metadata --profile spid-sp-metadata-public`

**Comment by damikael** [comment]
## Examples 

### Profiles for metadata validation

- saml2core
  - xsd_check
- spid-sp-metadata-base
  - test_EntityDescriptor
  - test_SPSSODescriptor
  - test_Signature
  - test_KeyDescriptor
  - test_SingleLogoutService
  - test_AssertionConsumerService
  - test_AttributeConsumingService
  - test_Organization 
- spid-sp-metadata-public
  - test_EntityDescriptor
  - test_SPSSODescriptor
  - test_Signature
  - test_KeyDescriptor
  - test_SingleLogoutService
  - test_AssertionConsumerService
  - test_AttributeConsumingService
  - test_Organization 
  - **test_ExtensionsContactPersonSPPublic**
- spid-sp-metadata-private
  - test_EntityDescriptor
  - test_SPSSODescriptor
  - test_Signature
  - test_KeyDescriptor
  - test_SingleLogoutService
  - test_AssertionConsumerService
  - test_AttributeConsumingService
  - test_Organization 
  - **test_ExtensionsContactPersonSPPrivate**
- spid-sp-metadata-pub-ag-full
  - test_EntityDescriptor
  - test_SPSSODescriptor
  - test_Signature
  - test_KeyDescriptor
  - test_SingleLogoutService
  - test_AssertionConsumerService
  - test_AttributeConsumingService
  - test_Organization 
  - **test_ExtensionsContactPersonAGFull**
- spid-sp-metadata-pub-ag-lite
  - test_EntityDescriptor
  - test_SPSSODescriptor
  - test_Signature
  - test_KeyDescriptor
  - test_SingleLogoutService
  - test_AssertionConsumerService
  - test_AttributeConsumingService
  - test_Organization 
  - **test_ExtensionsContactPersonAGLite**
- spid-sp-metadata-pub-op-full
  - test_EntityDescriptor
  - test_SPSSODescriptor
  - test_Signature
  - test_KeyDescriptor
  - test_SingleLogoutService
  - test_AssertionConsumerService
  - test_AttributeConsumingService
  - test_Organization 
  - **test_ExtensionsContactPersonOPFull**
- spid-sp-metadata-extra
  - test_Signature_extra
  - test_AttributeConsumingService_extra
  - test_SPSSODescriptor_extra
  - test_Organization_extra

### Profiles for request validation

- saml2core
  - test_xsd_and_xmldsig
- spid-sp-request-auth
  - test_AuthnRequest
  - test_Subject
  - test_Issuer
  - test_NameIDPolicy
  - test_Conditions
  - test_RequestedAuthnContext
  - test_Signature
  - test_RelayState
  - test_Scoping
  - test_RequesterID
- spid-sp-request-professional
  - test_AuthnRequest
  - test_Subject
  - test_Issuer
  - test_NameIDPolicy
  - test_Conditions
  - test_RequestedAuthnContext
  - test_Signature
  - test_RelayState
  - test_Scoping
  - test_RequesterID
  - **test_ExtensionsProfessionalUse**

**Comment by peppelinux** [comment]
All the tests marked in bold are a kind of feature request.
I can start doing a brand new profile management, each of the purposed brand new tests will be istructed with specialized PRs

**Comment by peppelinux** [comment]
the profiles names will be renamed as

saml2-sp
spid-sp-public (default)
spid-sp-private
spid-pub-ag-full
spid-pub-ag-lite
spid-sp-pub-op-full
spid-sp-extra

option --extra will be deprecated by spid-sp-extra

-metadata and -request have been removed because the tests of metadata and authrequests depends by the presence of --metadata-url and --authrequest-url CLI paramenters, if they are present the tests will be executed

many profiles can be tested in a single command, the report will give us any further detail for each profile

@damikael does this sound good to you?

**Comment by damikael** [comment]
A single profile contains either tests for metadata and tests for request and they are executed respectively if url for metadata or url for request is present as CLI parameter. Is it right?

**Comment by peppelinux** [comment]
Here the first implementation for selecting profile :
https://github.com/italia/spid-sp-test/commit/11136f6ae2f36fee0c2f7f4fa2544fc403c86d7a

This feature is not breakage with the legacy versions, default profile is spid sp public.
Something useful to know:

- extra parameter was not removed, actually it only works for metadata. AuthnRequest extras have been merged in AuthnRequestSPID
- All the test marked in bold in the comment of @damikael MUST be implemented in future

**Comment by peppelinux** [comment]
Implemented here
https://github.com/italia/spid-sp-test/releases/tag/v0.6.0

with the exclusion of **test_ExtensionsProfessionalUse**
