### ISSUE TITLE
Check for IPA code in ContactPerson for aggregated

### ISSUE THREAD

**Issue by damikael** [italia/spid-sp-test#28]
As for [Avviso SPID n.19 v4](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n19v4-regole_tecniche_aggregatori.pdf),
the element ContactPerson where contactType is "other" and entityType is "aggregated" must contain the element IPACode, if the element contains the attribute Public or PublicOperator. The element IPACode, if present, can not be empty and must be a valid code on IPA

**Comment by peppelinux** [comment]
I'm ok with that, I just need to ask you two things:

1. a valid metadata (example)
2. a unvalid metadata (example)

I'd use these in unit tests. Consider this feature done, just feed these two examples

**Comment by peppelinux** [comment]
Closed by https://github.com/italia/spid-sp-test/releases/tag/v0.6.0
