### ISSUE TITLE
Only one ORG MUST be present

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-sp-test#29]
https://github.com/italia/spid-sp-test/blob/a696bc434f8f82091c15a8a247729f827fa47654/src/spid_sp_test/metadata.py#L529

**Comment by damikael** [comment]
Only one Organization element MUST be present (==1)
not can be present (<=1)

**Comment by peppelinux** [comment]
sta qui
https://github.com/italia/spid-sp-test/commit/2eb2da8c843ef5382fbeb72b3cc89b6abcf6231e

che in italiano forse si capisce meglio :)

**Comment by damikael** [comment]
Ok scusa, facevo riferimento al riferimento precedente.
Occorre aggiornare anche la descrizione:
"Only one Organization element MUST be present - Avv.29 v.3"

**Comment by peppelinux** [comment]
ok
la seguiamo qui:
https://github.com/italia/spid-sp-test/issues/30

farò un commit unico per questa revisione generale del linguaggio normativo,
ottimo punto
