### ISSUE TITLE
More than one certificate in sp metadata

### ISSUE THREAD

**Issue by giafar** [italia/spid-sp-test#35]
According to https://github.com/italia/spid-sp-test/blob/62a351d719d55a46c6a4925263514371d4aadbe5/src/spid_sp_test/authn_request.py#L215 if the SP certificate is not the first one in the metadata the Authn signature validation fail.

**Comment by peppelinux** [comment]
Closed via https://github.com/italia/spid-sp-test/commit/ad8da48fb66e24e35f8e3eb7ea82d89d01382afc

now the check is in the loop :)
thank you @giafar
