### ISSUE TITLE
The Destination attribute must be a valid HTTPS url

### ISSUE THREAD

**Issue by pasqualecocchiero** [italia/spid-sp-test#37]
Buonasera. Sto effettuando i test di validazione col tool spid-saml-check e sono arrivato alla sezione Request->CheckStrict.
Il campo Destination della mia request è "http://localhost:8080" e questo genera l'errore "The Destination attribute must be a valid HTTPS url". Il problema è che l'url contiene una richiesta HTTP e non HTTPS (e quindi devo permettere anche richieste HTTPS a localhost) o l'errore è altrove?
Eventualmente sapreste dirmi a che punto dell'installazione di spid-saml-check viene effettuata l'assegnazione all'attributo Destination o come modificarlo?

**Comment by peppelinux** [comment]
Se hai qualche domanda o dubbio raggiungici su slack canale spid di Developers italia
