### ISSUE TITLE
the metadata signature MUST be valid

### ISSUE THREAD

**Issue by GoldMyr1994** [italia/spid-sp-test#40]
A lavoro stiamo cercando di imparere a usare SPID e poterlo integrare su un sito. 
Io utilizzo un pc Asus che in origine aveva windows e ci ho installato Ubuntu 20.04.2 LTS.

Ho generato i metadata utilizzando spid-php https://github.com/italia/spid-php

Ho effettuato la validazione utilzzando spid-sp-test e ho incontrato qualche problema con la validazione della signature.

Ho utilizzato spid-sp-test installandolo con pip seguendo le istruzioni nel README
Non risucivo a passare il test sulla validità della signature sui metadata. 

Chiedendo aiuto sulla comunity slack developer-italia(grazie dell'aiuto) sono stato prontamente aiutato e mi è stato detto che il file xml che stavo testando era valido ma che sulla mia macchina la validazione falliva probabilmente a causa della versione di `xmlsec` installata. 

Come da suggerimento ho riprovato spid-sp-test però utilizzando l'immagine docker e in questo caso sono stato in grado di verificare la validità dei metadata compresa la signature.

Sono state avanzate due ipotesi:
- fallisce su windows a causa della versione di xmlsec
- fallisce su ubuntu > 18 per una delle dipendenze di xmlsec

**Comment by peppelinux** [comment]
Ciao, su Windows che versione di xmlsec1 è installata?

**Comment by GoldMyr1994** [comment]
Sul pc che uso non c'è proprio più windows, l'ho completamente tolto per fare spazio ad ubuntu.
Facendo qualche tentativo in più listando i pacchetti installati ho trovato questo con `apt list | grep xmlsec`
```
libxmlsec1-dev/focal,now 1.2.28-2 amd64 [installato]
libxmlsec1-doc/focal,focal 1.2.28-2 all
libxmlsec1-gcrypt/focal,now 1.2.28-2 amd64 [installato, automatico]
libxmlsec1-gnutls/focal,now 1.2.28-2 amd64 [installato, automatico]
libxmlsec1-nss/focal,now 1.2.28-2 amd64 [installato, automatico]
libxmlsec1-openssl/focal,now 1.2.28-2 amd64 [installato]
libxmlsec1/focal,now 1.2.28-2 amd64 [installato, automatico]
xmlsec1/focal 1.2.28-2 amd64
```
Dato che non risultava installato l'ultimo ho abbastanza ignorantemente provato con `apt install xmlsec1` e ora riesco ad vedere tutti i test passati con successo anche senza usare l'immagine docker

Scusa ma non ho proprio la possibilità di fare test su un windows

**Comment by peppelinux** [comment]
ok, mancava nel readme fixato qui:
https://github.com/italia/spid-sp-test/commit/b2988e771f266d6537c6e823eb67c1425237fb73
