### ISSUE TITLE
Tests are different for SPID level 1 or 2 but ForceAuthn is always mandatory

### ISSUE THREAD

**Issue by matfur92** [italia/spid-sp-test#44]
Hi,
running a test on the same service provider (spid-express) with different values of SPID level (1 and 2) the number of tests is different but the ForceAuthn is always mandatory.
![image (9)](https://user-images.githubusercontent.com/10245779/121565613-e718f680-ca1c-11eb-99f3-245194f3769d.png)
Probably tests on ForceAuthn must be the same in both scenario.
What do you think?

**Comment by damikael** [comment]
https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf 
1.2.2.1. AUTHNREQUEST 

> nell’ elemento AuthnRequest devono essere presenti i seguenti attributi:
> ...
>  - l’attributo ForceAuthn nel caso in cui si richieda livelli di autenticazione superiori a SPIDL1 ( SPIDL2 o SPIDL3);

**Comment by peppelinux** [comment]
This bug comes from the legacy code:
https://github.com/italia/spid-saml-check/blob/648ba76b85c9163e19f04ba08e0be0ed25f3bae3/specs-compliance-tests/test/sp/authn_request_extra.py#L111

going to patch it in a hurry :)

**Comment by peppelinux** [comment]
Closed via https://github.com/italia/spid-sp-test/commit/340df965beab999c22fbac2dfa22ae4f12e28b98
