### ISSUE TITLE
Verify Scoping and RequesterID elements are ignored

### ISSUE THREAD

**Issue by damikael** [italia/spid-sp-test#49]
<Scoping> and <RequesterID> elements, if present in the AuthnRequest, should be ignored.

**Comment by peppelinux** [comment]
Yes, that's true, When I read the AT LG AA SAML2 profile I saw that Scoping were used ...
I believe that those checks are completely useless for our profile, Looks good to me right now!

fixed here:
https://github.com/italia/spid-sp-test/commit/e5e7391b0e9f20f7ce542dc3e2dd4a48ecd0d027
