### ISSUE TITLE
eIDAS node compatibility

### ISSUE THREAD

**Issue by damikael** [italia/spid-sp-test#50]
If AuthnContextClassRef of AuthnRequest is SpidL2 or SpidL3, and the related SP metadata id for public organization (<spid:Public/>) the SP metadata should be checked for the presence of eIDAS-specific AttributeConsumingServices (index 99 and 100)

**Comment by peppelinux** [comment]
Hooo, finally something interesting here!
the answer is YES, we must have it

**Comment by mauromol** [comment]
If this becomes a requirement for SPID, it means that:
- a public administration cannot offer eIDAS access with a native eIDAS SP, but must use FICEP (or at least it must declare so in its SPID metadata)
- a public administration cannot offer eIDAS access (either with FICEP or not) using a separate metadata file (or at least it must include FICEP metadata fragment in its SPID metadata file)

Is this really the desired result?

**Comment by peppelinux** [comment]
1. yes
2. I'd suggest to use a separate metadata

**Comment by peppelinux** [comment]
Here eIDAS Ficep profile 
https://github.com/italia/spid-sp-test/commit/b2fbbfe642c1ca4bd5f8ec39c5158a7b13ae73e9

implemented
