### ISSUE TITLE
Verify the SP metadata signature

### ISSUE THREAD

**Issue by damikael** [italia/spid-sp-test#51]
See: https://github.com/italia/spid-saml-check/issues/97

**Comment by peppelinux** [comment]
Actually I adopt the same, or quite similar, approach already adopted by @psmiraglia 
https://github.com/italia/spid-sp-test/blob/b4fc2b515219e697f1da4ca2ae1a23719808c3d1/src/spid_sp_test/metadata.py#L204
and, according to xmlsec1 docs it's a valid approach.

The resulting xmlsec1 command is 

````
spid_sp_test --metadata-url https://localhost:8000/spid/metadata --extra  --authn-url https://localhost:8000/spid/login/?idp=http://localhost:8080 --debug ERROR -tr


> ~/DEV/DTD/Spid/spid-sp-test/src/spid_sp_test/metadata.py(208)test_xmldsig()
-> is_valid = True
(Pdb) cmd

'xmlsec1 --verify --insecure --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntityDescriptor /tmp/tmplrqdfscl'
````
