### ISSUE TITLE
Remove empty AttributeStatement element when no attributes

### ISSUE THREAD

**Issue by damikael** [italia/spid-sp-test#53]
Evaluate if this fix is avaluable for spid-sp-test too:
https://github.com/italia/spid-saml-check/commit/9b29f2bc4c4d7959b6c0cbb8d492d5ca3d609796

**Comment by peppelinux** [comment]
Yes
https://github.com/italia/spid-sp-test/blob/18c5d96d39182d46092f9086f4bbebd7859ca145/src/spid_sp_test/response.py#L73

As you can see, for each attributes there Will be loaded a template and a value rendering in It.

If they are not available ... Nothing happens!
