### ISSUE TITLE
Method, content type and body not used to retrieve AuthnRequest when executing Response tests

### ISSUE THREAD

**Issue by mauromol** [italia/spid-sp-test#64]
Follow-up to #62.

When I test my SP using POST requests to obtain the `AuthnRequest`, although the `AuthRequest` checks are executing successfully, adding `-tr` to perform the response tests causes spid_sp_test to fail with:

```
Traceback (most recent call last):
  File "/home/mauro/workspace/python-env/spid_sp_test/bin/spid_sp_test", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/mauro/git/spid-sp-test/src/spid_sp_test/spid_sp_test", line 317, in <module>
    selective_run(response_check, profile, args.list)
  File "/home/mauro/git/spid-sp-test/src/spid_sp_test/spid_sp_test", line 31, in selective_run
    method()
  File "/home/mauro/git/spid-sp-test/src/spid_sp_test/../spid_sp_test/response.py", line 320, in test_profile_spid_sp
    self.do_authnrequest()
  File "/home/mauro/git/spid-sp-test/src/spid_sp_test/../spid_sp_test/response.py", line 156, in do_authnrequest
    self.authn_request_data = get_authn_request(
  File "/home/mauro/git/spid-sp-test/src/spid_sp_test/../spid_sp_test/authn_request.py", line 155, in get_authn_request
    raise Exception(
Exception: Authn Request page returns a HTML error code: 405
```

Example invocation:

```
spid_sp_test --metadata-url http://mysp.com:8110/path/to/metadata.xml --authn-url http://mysp.com:8110/path/to/login -rm POST -rct data -rb '{"authId": "test", "serviceProviderId": "mysp", "myacs": "cdd", "identityProviderEntityId": "https://localhost:8080"}' --extra -report -o spid -rf html -tr
```

**Comment by peppelinux** [comment]
Here
https://github.com/italia/spid-sp-test/blob/060f9def062e65ded2e3737c1f8643067adede73/src/spid_sp_test/response.py#L156

We must include these parameters
https://github.com/italia/spid-sp-test/blob/060f9def062e65ded2e3737c1f8643067adede73/src/spid_sp_test/authn_request.py#L101

Passing them from here
https://github.com/italia/spid-sp-test/blob/060f9def062e65ded2e3737c1f8643067adede73/src/spid_sp_test/spid_sp_test#L314

As already done here
https://github.com/italia/spid-sp-test/blob/060f9def062e65ded2e3737c1f8643067adede73/src/spid_sp_test/spid_sp_test#L287

And It Will work

**Comment by peppelinux** [comment]
Ah, once have passed them we must storie them as attributes, here
https://github.com/italia/spid-sp-test/blob/060f9def062e65ded2e3737c1f8643067adede73/src/spid_sp_test/response.py#L149

**Comment by peppelinux** [comment]
Done here
https://github.com/italia/spid-sp-test/pull/67

**Comment by peppelinux** [comment]
closed by
https://github.com/italia/spid-sp-test/releases/tag/v0.9.5
