### ISSUE TITLE
EntityID MUST be equal to the metadata download URL warning

### ISSUE THREAD

**Issue by mauromol** [italia/spid-sp-test#66]
I know we've discussed this on slack @peppelinux, but I decided to also track it here.

Testing my SP with spid-sp-test brings this warning:

> The EntityID MUST be equal to http://testhost.localdomain:8110/path/to/metadata.xml (while it is https://spid.production-host.it/sp/myspid)

Yes, it's a warning by now: will it become a requirement? (that "MUST" scares me, honestly).

I could not find either in SAML or in SPID specifications any track of this requirement. SAML specification says that entity ids are URIs, i.e. Uniform Resource Identifiers. The purpose of URIs is to uniquely identify a resource within some scope: in this case, it allows to identify a SP or IdP within a SAML federation. The SPID specification itself says that entity IDs (for SPs, IdPs and attribute authorities) should be URIs (chapters 1.3.2, 1.2.2.4 and 2.2.4 respectively).
A URL is a special kind of URI, and it's the most commonly used (although SAML itself also uses URNs a lot). So, requiring entity IDs to be URLs is a somewhat acceptable restriction, but forcing them to be equal to the URL from which metadata can be downloaded is a strong requirement, which mixes interoperability requirements with implementation details.
We're mixing URIs with URLs. I like to think about entity IDs like XML namespaces: schemas are not necessarily published at the URIs/URLs representing their target namespaces!!

What if a SP (with its own existing entity ID which should be ideally maintained forever) needs to move its servers and change the URL where metadata are exposed? What if the company providing the SP infrastructures changes its name (and hence its registered domain)?
What if a complex implementation strategy requires to publish metadata at different URLs, especially when aggregators and/or proxies are involved?

As a final notice, please note that the warning is not saying that the metadata "should be downloadable at the URL representing the entity id" (which may be considered as a "nice to have" good practice), but that, on the contrary, the entity id MUST be equal to the URL at which metadata is exposed: which is way stronger and weird.

**Comment by peppelinux** [comment]
from v0.9.6 this "warning" was moved to extra checks that are not mandatories for onboarding if I'm not wrong

@damikael ^

**Comment by damikael** [comment]
Yes, it's not a SPID requirement. Furthermore description was changed in "EntityID SHOULD be equal to the metadata download URL"

**Comment by peppelinux** [comment]
> Yes, it's not a SPID requirement. Furthermore description was changed in "EntityID SHOULD be equal to the metadata download URL"

yes, here in the current release
https://github.com/italia/spid-sp-test/blob/10917dd825856e838944b0395972b2ff37cac345/src/spid_sp_test/metadata_extra.py#L28
