### ISSUE TITLE
Response test 31 expected result

### ISSUE THREAD

**Issue by mauromol** [italia/spid-sp-test#73]
Currently spid-sp-test expects an "OK" result for test 31 when running in one of the SPID profile modes:

```
ERROR:spid_sp_test:Test [31] L'attributo Format di Issuer deve essere omesso o assumere valore urn:oasis:names:tc:SAML:2.0:nameid-format:entity. In questo test il valore è omesso. Risultato atteso: Ok: [http status_code: 422]
```

However, although being controversial, current SPID specification mandates the use of an explicit `Format` attribute equal to `urn:oasis:names:tc:SAML:2.0:nameid-format:entity` (there's a dedicated open issue at https://github.com/italia/spid-regole-tecniche/issues/51 for this). The current implementation of spid-saml-check hence requires a KO here, coherently with the SPID specification.

Hence, my implementation, which validates correctly with spid-saml-check, has been specifically tuned to REQUIRE an explicit `Format` attribute in issuers.

So, spid-sp-test should expect a KO result from test 31, at least as long as the SPID specification doesn't get changed (if ever).

**Comment by peppelinux** [comment]
Hi @mauromol 
It seems to me that actually spid-s-test have the same behaviour of spid-saml-check, did I have misunderstand this issue?

**Comment by mauromol** [comment]
@peppelinux not really, because our implementation passed the spid-saml-check assessment, while it fails this check in spid-sp-check.

This said, your last comment in https://github.com/italia/spid-regole-tecniche/issues/51#issuecomment-888936205 made me learn something new: the `Response.Issuer` is the only `Issuer` where the `Format` can be omitted, as per SPID specifications!! It's mandatory for the `AuthnRequest` and for the `Assertion`, as well as for the interactions with attribute authorities...

So yes, the expected result from spid-sp-test is then correct, although the description of the test shuold clearly highlight that we're talking about the `Response` issuer (as opposed to the `Assertion` issuer, for which an explicit `Format` is unfortunately required as of now).

I may propose a PR to adjust the test description, if you wish.

**Comment by peppelinux** [comment]
closed by
https://github.com/italia/spid-sp-test/pull/76
